corrected formatting issues removed broken workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -69,25 +69,6 @@ jobs:
   #       run: |
   #         bats test/
 
-  security:
-    name: Security Scan with bash-security
-    runs-on: ubuntu-latest
-
-    steps:
-      # Checkout code
-      - name: Checkout Code
-        uses: actions/checkout@v3
-
-      # Install bash-security
-      - name: Install bash-security
-        run: |
-          pip install bash-security
-
-      # Run bash-security
-      - name: Run bash-security Scan
-        run: |
-          bash-security scan .
-
   validate_permissions:
     name: Validate File Permissions and Shebangs
     runs-on: ubuntu-latest
@@ -105,7 +86,8 @@ jobs:
       # Validate all scripts have a shebang
       - name: Validate Shebangs
         run: |
-          missing_shebangs=$(find . -name "*.sh" ! -exec head -n 1 {} \; | grep -v "^#!")
+          missing_shebangs=$(find . -name "*.sh" ! -path "./dot/bash-preexec.sh" ! -path "./another/ignored-file.sh" -exec sh -c 'head -n 1 "$1" | grep -q "^#!" || echo "Missing shebang: $1"' _ {} \;
+)
           if [[ -n "$missing_shebangs" ]]; then
             echo "The following files are missing a shebang:"
             echo "$missing_shebangs"
